package PackageLab01;


import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class grafico extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public int x=0;
    //ABin a = new ABin();
    public grafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        tabla = new javax.swing.JPanel();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salida.setEditable(false);
        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane1.setViewportView(salida);

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setPreferredSize(new java.awt.Dimension(800, 425));

        javax.swing.GroupLayout tablaLayout = new javax.swing.GroupLayout(tabla);
        tabla.setLayout(tablaLayout);
        tablaLayout.setHorizontalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        tablaLayout.setVerticalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        Volver.setText("volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1))
                    .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //ABin a = new ABin();
    
   
    public void dibujar(NodosUsuario Nodo, Bloque block, int dir, int difx, int dify) {
        
        Graphics g = tabla.getGraphics();
        if (Nodo == null) {
            return;
        } else {
            if(dir==0){ 
              g.setColor(Color.white);
              g.fillOval(400, 30, 25, 25);
              g.setColor(Color.black);
              g.drawOval(400, 30, 25, 25);
              g.setColor(Color.BLACK);
              g.drawString(Nodo.ID+"", 409 , 47 );
            }
            
            if(dir==1){ 
              g.setColor(Color.red);
              g.drawLine(412+difx, 42+dify,412+difx+30, 42+dify-30);
              g.setColor(Color.white);
              g.fillOval(400+difx, 30+dify, 25, 25);
              g.setColor(Color.black);
              g.drawOval(400+difx, 30+dify, 25, 25);
              g.setColor(Color.BLACK);
              g.drawString(Nodo.ID+"", 409+difx , 47+dify );
            }
            
            if(dir==2){ 
              g.setColor(Color.red);
              g.drawLine(412+difx, 42+dify,412+difx-30, 42+dify-30);
              g.setColor(Color.white);
              g.fillOval(400+difx, 30+dify, 25, 25);
              g.setColor(Color.black);
              g.drawOval(400+difx, 30+dify, 25, 25);
              g.setColor(Color.BLACK);
              g.drawString(Nodo.ID+"", 409+difx , 47+dify );
            }
            
            dibujar(Nodo.LI,block,1,-40+difx,40+dify);
            
            dibujar(Nodo.LD,block,2,40+difx,40+dify);
        }
    }
      
      
    
    
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea salida;
    private javax.swing.JPanel tabla;
    // End of variables declaration//GEN-END:variables
}
